#!/usr/bin/env python3
"""Token ledger for PocketMagic multi-agent work.

Commands:
  log <agent> <input_tokens> <output_tokens> "<description max 40 chars>"
      Append one session row to .agents/agent_<agent>_consumed_tokens.md.
      Run at the END of every working session by the agent itself.

  summarize
      Rebuild the root total_tokensconsumed.md from every agent ledger and
      refresh the 'This application was made with N tokens' line in README.md.
      Run on every merge to main (and before opening a PR, to quote numbers).

Numbers must come from the harness session totals (OpenCode usage display).
Never estimate. Never log another agent's session.
"""
from __future__ import annotations

import argparse
import datetime
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
AGENTS_DIR = ROOT / ".agents"
TOTAL_FILE = ROOT / "total_tokensconsumed.md"
README_FILE = ROOT / "README.md"

AGENTS = [
    "build",
    "plan",
    "troubleshoot",
    "implement",
    "kubernetes-specialist",
    "devops",
    "guidance-agent",
]

ROW_RE = re.compile(
    r"^\|\s*(\d{4}-\d{2}-\d{2} \d{2}:\d{2})\s*"   # date/time
    r"\|\s*(\d+)\s*"                               # input
    r"\|\s*(\d+)\s*"                               # output
    r"\|\s*(\d+)\s*"                               # session total
    r"\|\s*(.{1,40})?\s*\|"                        # description (<=40)
)


def ledger_path(agent: str) -> pathlib.Path:
    return AGENTS_DIR / f"agent_{agent}_consumed_tokens.md"


def cmd_log(args: argparse.Namespace) -> None:
    desc = args.description.strip()
    if len(desc) > 40:
        sys.exit(f"error: description is {len(desc)} chars; limit is 40")
    if args.agent not in AGENTS:
        sys.exit(f"error: unknown agent '{args.agent}'; known: {', '.join(AGENTS)}")

    path = ledger_path(args.agent)
    if not path.exists():
        sys.exit(f"error: missing ledger {path}; restore it from git")
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    row = f"| {ts} | {args.input} | {args.output} | {args.input + args.output} | {desc} |\n"
    with path.open("a", encoding="utf-8") as fh:
        fh.write(row)
    print(f"logged: {row.strip()}")


def parse_rows(path: pathlib.Path) -> list[tuple[str, str, str, str, str]]:
    rows: list[tuple[str, str, str, str, str]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = ROW_RE.match(line.strip())
        if m:
            rows.append(m.groups())
    return rows


def patch_readme(total: int) -> None:
    text = README_FILE.read_text(encoding="utf-8") if README_FILE.exists() else ""
    line = f"This application was made with {total:,} tokens".replace(",", "")
    new_text, count = re.subn(
        r"This application was made with \d+ tokens",
        line,
        text,
    )
    if count == 0:
        if text and not text.endswith("\n"):
            text += "\n"
        new_text = text + f"\n---\n\n{line}\n"
    README_FILE.write_text(new_text, encoding="utf-8")


def cmd_summarize(_: argparse.Namespace) -> None:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    grand_in = grand_out = grand_sessions = 0
    body: list[str] = [
        "# Total Tokens Consumed",
        "",
        "Unified totals from every agent ledger in `.agents/agent_*_consumed_tokens.md`.",
        "Regenerated by `scripts/token_ledger.py summarize` on every merge to `main`.",
        "",
        "| Agent | Sessions | Input Tokens | Output Tokens | Total |",
        "| :--- | ---: | ---: | ---: | ---: |",
    ]
    for agent in AGENTS:
        rows = parse_rows(ledger_path(agent))
        tin = sum(int(r[1]) for r in rows)
        tout = sum(int(r[2]) for r in rows)
        grand_in += tin
        grand_out += tout
        grand_sessions += len(rows)
        body.append(f"| {agent} | {len(rows)} | {tin:,} | {tout:,} | {tin + tout:,} |")
    body += [
        f"| **TOTAL** | **{grand_sessions}** | **{grand_in:,}** | **{grand_out:,}** "
        f"| **{grand_in + grand_out:,}** |",
        "",
        f"_Last updated: {now}_",
        "",
    ]
    TOTAL_FILE.write_text("\n".join(body), encoding="utf-8")
    patch_readme(grand_in + grand_out)
    rel_total = TOTAL_FILE.relative_to(ROOT)
    rel_readme = README_FILE.relative_to(ROOT)
    print(f"wrote {rel_total} and refreshed {rel_readme} footer "
          f"(sessions={grand_sessions}, in={grand_in:,}, out={grand_out:,})")


def main() -> None:
    parser = argparse.ArgumentParser(description="PocketMagic token ledger")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_log = sub.add_parser("log", help="append one session row to an agent ledger")
    p_log.add_argument("agent", choices=AGENTS)
    p_log.add_argument("input", type=int, help="input tokens from the harness session totals")
    p_log.add_argument("output", type=int, help="output tokens from the harness session totals")
    p_log.add_argument("description", help="what was done, 40 characters maximum")
    p_log.set_defaults(func=cmd_log)

    p_sum = sub.add_parser("summarize", help="rebuild total_tokensconsumed.md and README footer")
    p_sum.set_defaults(func=cmd_summarize)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
